set(output "${CMAKE_CURRENT_BINARY_DIR}/字符画导出.png")
file(REMOVE "${output}")
execute_process(COMMAND "${PROGRAM}" "${INPUT}" --format png --output "${output}"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT result EQUAL 0 OR NOT stdout STREQUAL "" OR NOT stderr STREQUAL "")
    message(FATAL_ERROR "PNG export failed: ${result}: ${stderr}")
endif()
file(READ "${output}" signature LIMIT 8 HEX)
if(NOT signature STREQUAL "89504e470d0a1a0a")
    message(FATAL_ERROR "Invalid PNG signature")
endif()
file(SHA256 "${output}" before)
execute_process(COMMAND "${PROGRAM}" "${INPUT}" --format png --output "${output}"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
file(SHA256 "${output}" after)
if(NOT result EQUAL 1 OR NOT before STREQUAL after)
    message(FATAL_ERROR "Existing output must be preserved")
endif()
execute_process(COMMAND "${PROGRAM}" "${INPUT}" --format png
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(NOT result EQUAL 2)
    message(FATAL_ERROR "Missing PNG output must be a usage error")
endif()
file(REMOVE "${output}")
